org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.4
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.03
maven_group=com.pythemcio
archives_base_name=pythemcio

# Dependencies
fabric_api_version=0.119.4+1.21.4
